# Generated by Django 5.0.6 on 2024-05-29 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Student ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('not_enrolled', 'Not Enrolled')], max_length=20, verbose_name='Enrollment Status')),
                ('section', models.CharField(choices=[('BSIT 2-A Algorithm', 'BSIT 2-A Algorithm'), ('BSIT 2-B Pseudocode', 'BSIT 2-B Pseudocode')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ap3', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='AP 3')),
                ('cc225', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='CC 225')),
                ('cc225L', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='CC 225 L')),
                ('gec_tcw', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='GEC-TCW')),
                ('pelec3', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P-Elec 3')),
                ('pc223', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PC 223')),
                ('pc224', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PC 224')),
                ('pe4', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PE 4')),
                ('average', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Average')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradeCalculator.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeansLister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('section', models.CharField(choices=[('BSIT 2-A Algorithm', 'BSIT 2-A Algorithm'), ('BSIT 2-B Pseudocode', 'BSIT 2-B Pseudocode')], max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradeCalculator.studentinfo')),
            ],
        ),
    ]
