# Generated by Django 5.0.6 on 2024-05-29 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradeCalculator', '0002_alter_grade_ap3_alter_grade_cc225_alter_grade_cc225l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ap3',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='AP 3'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='cc225',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='CC 225'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='cc225L',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='CC 225 L'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gec_tcw',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='GEC-TCW'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pc223',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PC 223'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pc224',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PC 224'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pe4',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='PE 4'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pelec3',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P-Elec 3'),
        ),
    ]
