# Generated by Django 5.0.6 on 2024-05-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradeCalculator', '0003_alter_grade_ap3_alter_grade_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='enrollment_status',
        ),
    ]
